//HASHING with Chaining method to handle the Collissions
//Hashing of student record based on birth date as the key
#include<stdio.h>
#include<stdlib.h>
#define records 100
//supports hashing of 100 records
struct info
{
	long unsigned int bday;
	char name[11];
	float cgpa;
	char clg[4];
	struct info* link;
};

typedef struct info INFO;

INFO *getinfo(INFO *p)
{
	printf("Enter name:");
	scanf("%s",p->name);
	printf("Enter CGPA");
	scanf("%f",&p->cgpa);
	printf("Enter college code");
	scanf("%s",p->clg);
	return p;
}

int hash(long unsigned int bd)
{	/*The hash function is generated by extracting the day month and last 2 digits of the birthdate and 
	combining these three.
	The value obtained is divided by 29, a prime number to increase the randomization  */
	int a,b,c,value;
	a = bd / 1000000;
	b = (bd - a)/10000;
	c = bd % 10;
	value = a/10 + a%10 + b/10 + b%10 + c;
	value %=29;
	return value;
}

void display(INFO *p)
{
	printf("\nBirth Date:%lx",p->bday);
	printf("\nName: %s",p->name);
	printf("\nCGPA: %f",p->cgpa);
	printf("\nCollege:%s\n",p->clg);
}

void search(INFO *table[],long unsigned int bday)
{
	INFO *p;
	p = table[hash(bday)];
	while(p!=NULL && p->bday != bday)
		p = p->link;
	if(p == NULL)
	{
		printf("\nRecord not found");
		return;
	}
	display(p);
}
	
void main()
{
	INFO *table[30];
	int i,ch;
	for(i=0;i<30;i++)
	{	
		//table[i] = (INFO *)malloc(sizeof(INFO));
		table[i] = NULL;
	}
	long unsigned int bd;
	int value;
	for(i=0;i<records;i++)
	{	
		printf("\nEnter birthday");
		scanf("%lx",&bd);
		printf("%lx",bd);
		
		INFO *p = (INFO *)malloc(sizeof(struct info));
		INFO *q,*r;
		p->bday = bd;
		p->link = NULL;
		p = getinfo(p);
		value = hash(bd);
		//table[value] = p;
		if(table[value] == NULL)
			table[value] = p;
		else
		{
			q = table[value];
			table[value] = p;
			p->link = q;
		}
		
			
	}
	
	
	while(1)
	{
		printf("\nEnter 1 to search");
		scanf("%d",&ch);
		if(ch==1)
		{
			printf("\nEnter birth date:");
			scanf("%lx",&bd);
			//value = hash(bd);
			search(table,bd);
		}
		else
			return;
	}
	
}
